packages:
  - apps/*
  - packages/*
  - emulator
catalog:
  prettier: ^3.5.3
  eslint: ^9.27.0
  typescript: ^5.8.2
  zod: ^3.25.47
  "@trpc/server": ^11.2.0
  "@trpc/client": ^11.2.0
  "@trpc/tanstack-react-query": ^11.2.0
  "@tanstack/react-query": ^5.79.0
  "@supabase/supabase-js": ^2.49.8
  fastify: ^5.3.3
  tsx: ^4.19.4
  superjson: "^2.2.2"
  vitest: ^3.2.1
  "drizzle-orm": "^0.44.1"
  "drizzle-zod": "^0.8.2"
  "postgres": "^3.4.7"
  "drizzle-kit": "^0.31.1"
  "@types/node": "^20.17.57"
  "dotenv-cli": "^8.0.0"
  "wait-on": "^8.0.3"
onlyBuiltDependencies:
  - supabase
