name = "satopod-farm-reviewer"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2025-06-17"

[vars]

DATABASE_URL = "<YOUR_DATABASE_URL>"
DISCORD_ENCRYPTION_KEY = "<YOUR_DISCORD_ENCRYPTION_KEY>"

[env.daily]
name = "satopod-farm-reviewer-daily"
main = "src/daily/index.ts"
triggers.crons = [
  "0 0 * * *", # Runs daily at midnight UTC
]
