name: Production Deployment

on:
  push:
    branches:
      - "releases/**"

jobs:
  deploy-database:
    name: Deploy Database Schema
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Push database schema
        run: pnpm db:migrate
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

  deploy-api:
    name: Deploy API
    runs-on: ubuntu-latest
    timeout-minutes: 60
    needs: deploy-database

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build & Deploy Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: "apps/api"
          command: "deploy src/daily/index.ts --config ../../infra/cloudflare/api/wrangler.toml"

  deploy-reviewer:
    name: Deploy Reviewer Scheduler
    runs-on: ubuntu-latest
    timeout-minutes: 60
    needs: deploy-database

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build & Deploy Daily Scheduled Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: "apps/reviewer"
          command: "deploy src/app.ts --config ../../infra/cloudflare/reviewer/wrangler.toml --env daily"

  deploy-dashboard:
    name: Deploy Dashboard
    runs-on: ubuntu-latest
    needs: deploy-api
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build & Deploy Daily Scheduled Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: "apps/dashboard"
          command: "pnpm cf:deploy"
          packageManager: "pnpm"
