name: Unit Tests

on:
  pull_request:
    branches: [develop]
    paths-ignore:
      - ".github/workflows/**"
      - "*.md"
      - "*ignore"
      - "*.yaml"
      - "*.yml"
      - "docs/**"

# 同じPRまたはブランチで複数のunit testが実行されないようにする
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-workspace

      - name: Run unit tests
        run: pnpm test:ci
