name: Unit Tests and E2E Tests

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]
    paths-ignore:
      - ".github/workflows/**"
      - "*.md"
      - "*ignore"
      - "*.json"
      - "*.yaml"
      - "*.yml"
      - "infra/**"
      - "docs/**"

# develop->mainのPRで複数のE2Eテストが同時実行されないようにする
# E2Eテストは時間が長く、リソースを大量に消費するため
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit-and-e2e-tests:
    name: Unit Tests and E2E Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-workspace

      - name: Run unit tests
        run: pnpm test:ci

      - name: Run E2E tests
        timeout-minutes: 60
        run: pnpm e2e:ci

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: packages/e2e-tests/playwright-report/
          retention-days: 30
