name: Unit Tests and E2E Tests

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]
    paths-ignore:
      - ".github/workflows/**"
      - "*.md"
      - "docs/**"

# develop->mainのPRで複数のE2Eテストが同時実行されないようにする
# E2Eテストは時間が長く、リソースを大量に消費するため
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit-and-e2e-tests:
    name: Unit Tests and E2E Tests
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run unit tests
        run: pnpm test:ci

      - name: Run E2E tests
        run: pnpm e2e:ci

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: packages/e2e-tests/playwright-report/
          retention-days: 30
